spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${redis.host}
    port: ${redis.port}

upload:
  image:
    location: /Users/yoon/Desktop/image/
